### ISSUE TITLE
Not work on WP 4.7

### ISSUE THREAD

**Issue by redwon** [mattiasghodsian/wp_theme_settings#4]
Warning: Invalid argument supplied for foreach() in site.dev\wp-content\themes\flowers\wp_theme_settings.php on line 193

Code in functions.php : your example

**Comment by mattiasghodsian** [comment]
[https://github.com/mattiasghodsian/wp_theme_settings/commit/1babd3861f08314ed1d60a9f5156a486f8767953](https://github.com/mattiasghodsian/wp_theme_settings/commit/1babd3861f08314ed1d60a9f5156a486f8767953)
