### ISSUE TITLE
Missing Changelog causing repeated PHP timeouts

### ISSUE THREAD

**Issue by 508LoopDetected** [mattiasghodsian/wp_theme_settings#5]
I recently noticed a great deal of slowdown on the sites I'm using your system with. It turned out to be an issue with the **get_wpts_git_version** function in wp_theme_settings.php, lines 423 + 424. The changelog file (http://wpts.nexxoz.com/changelog.txt) and your website in general seem to be currently unavailable, so the file_get_contents command keeps timing out. The rest of the WP installation reacts by loading very sluggishly on both front-end and the admin side. Clearing out the function works fine as a temporary solution, but I wanted to post this anyway in case you weren't aware your site was down.

Thanks for creating WPTS, by the way. You've turned a daunting experience into a much simpler process. Great stuff!

**Comment by mattiasghodsian** [comment]
Yes im aware of this and its fixed for now, Im moving my sites soon and im happy you like WPTS

**Comment by 508LoopDetected** [comment]
Hello -- Perhaps you're already aware, but I've just noticed the same issue has popped back up today. Seems your site might be down again. A few of my client sites were loading extremely slowly, but disabling the function from above temporarily remedied the problem.

**Comment by mattiasghodsian** [comment]
@themilstead Yes i´m well aware,  i´m moving all my sites (will have some down time for a few days). Thanks you for the report.
