### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by bartje1994** [mattiasghodsian/wp_theme_settings#6]
Warning: Invalid argument supplied for foreach() in site.dev\wp-content\themes\flowers\wp_theme_settings.php on line 193

I used your example in my theme functions.php, i don't know what i do wrong.

**Comment by mattiasghodsian** [comment]
New update is released.
[https://github.com/mattiasghodsian/wp_theme_settings/commit/1babd3861f08314ed1d60a9f5156a486f8767953](https://github.com/mattiasghodsian/wp_theme_settings/commit/1babd3861f08314ed1d60a9f5156a486f8767953)
