### ISSUE TITLE
Warning: Illegal string offset 'name' 

### ISSUE THREAD

**Issue by ehsanmusavi** [mattiasghodsian/wp_theme_settings#7]
Hi, I get this error for every type of input I want to add:
Warning: Illegal string offset 'name' in C:\xampp\htdocs\wordpress\wp-content\themes\test\wp_theme_settings.php on line 57

**Comment by ghost** [comment]
can i see your code ?

**Comment by ehsanmusavi** [comment]
I removed it but I tried many times with every input type. Can you give me a working example code?

**Comment by mattiasghodsian** [comment]
You are missing the key name, check the [child theme](https://github.com/mattiasghodsian/wp_theme_settings/blob/master/twentyseventeen-child/functions.php) for examples and read the [documentation](http://wpts.nexxoz.com/docs.php)
