### ISSUE TITLE
Google Adsense codes do not work in text fields

### ISSUE THREAD

**Issue by anton-team** [mattiasghodsian/wp_theme_settings#8]
This really is fascinating, the most complete I've seen.

Congratulations.

I open this comment because despite all the great benefits, there is something I need and is that, when it comes to adding Google Adsense codes in the fields, they do not work, I think the script tries to run the GA code.

If only I could add the external scripts in the fields, I would feel more grateful.

**Comment by mattiasghodsian** [comment]
Have any examples?

**Comment by anton-team** [comment]
Yes, you can see it.

https://cl.ly/965a19621dbc

**Comment by mattiasghodsian** [comment]
> Yes, you can see it.
> 
> https://cl.ly/965a19621dbc

This is probably happening because the input fields are sanitized, take a look [here](https://github.com/mattiasghodsian/wp_theme_settings/blob/eb4fd8c0bee854e214c9487b6478731f71b109f5/wp_theme_settings.php#L402-L404)
